requires:
  - https://github.com/moremoban/pypi-mobans.git
configuration:
  template_dir:
  - "pypi-mobans:templates"
  - ".moban.d"
  configuration: echarts-dbapac-pypkg.yml
targets:
  - README.rst: CUSTOM_README.rst.jj2
  - setup.py: custom_setup.py.jj2
  - requirements.txt: requirements.txt.jj2
  - "tests/requirements.txt": "tests/custom_requirements.txt.jj2"
  - "docs/source/conf.py": "docs/source/conf.py.jj2"
  - test.sh: test.script.jj2
  - "echarts_dbapac_pypkg/_version.py": "_version.py.jj2"
  - .gitignore: gitignore.jj2
  - .travis.yml: travis.yml.jj2
